Exercici 1
Carregar “data” i "features" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [10]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data  
features = iris.feature_names  
print("Els 10 primers registres de les dades:")
print(data[:10])
print("Els 10 primers noms de les característiques:")
print(features[:10])

Els 10 primers registres de les dades:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Els 10 primers noms de les característiques:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [2]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data  
feature_names = iris.feature_names  
df_data = pd.DataFrame(data, columns=feature_names)

print("Els 10 primers registres de les dades:")
print(df_data.head(10))

Els 10 primers registres de les dades:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1


Exercici 2
Concatena “data” i “features” en un nou array. Mostra els 5 primers registres.

In [3]:
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data  
features = iris.feature_names  

dades_concatenades = np.column_stack((data, iris.target))
dades_concatenades = np.column_stack((dades_concatenades, iris.target_names[iris.target]))

print("Els 5 primers registres del nou array:")
print(dades_concatenades[:5])

Els 5 primers registres del nou array:
[['5.1' '3.5' '1.4' '0.2' '0.0' 'setosa']
 ['4.9' '3.0' '1.4' '0.2' '0.0' 'setosa']
 ['4.7' '3.2' '1.3' '0.2' '0.0' 'setosa']
 ['4.6' '3.1' '1.5' '0.2' '0.0' 'setosa']
 ['5.0' '3.6' '1.4' '0.2' '0.0' 'setosa']]


Exercici 3
Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.

In [3]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data 

sepal_length_index = features.index('sepal length (cm)')
petal_length_index = features.index('petal length (cm)')

sepal_length = data[:, sepal_length_index]
petal_length = data[:, petal_length_index]

mean_sepal_length = np.mean(sepal_length)
mean_petal_length = np.mean(petal_length)
std_sepal_length = np.std(sepal_length)
std_petal_length = np.std(petal_length)

print("La mitjana de la longitud del sèpal és de : {:.2f} cm".format(mean_sepal_length))
print("La mitjana de la longitud del pètal és de: {:.2f} cm".format(mean_petal_length))
print("La desviació estàndard de la longitud del sèpal és de: {:.2f} cm".format(std_sepal_length))
print("La desviació estàndard de la longitud del pètal és de: {:.2f} cm".format(std_petal_length))

La mitjana de la longitud del sèpal és de : 5.84 cm
La mitjana de la longitud del pètal és de: 3.76 cm
La desviació estàndard de la longitud del sèpal és de: 0.83 cm
La desviació estàndard de la longitud del pètal és de: 1.76 cm


Exercici 4
Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

In [5]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data 

num_samples = 20
random_indices = np.random.choice(data.shape[0], num_samples, replace=False)
random_sample = data[random_indices]

print("Mostra aleatòria de 20 registres:")
print(random_sample)

Mostra aleatòria de 20 registres:
[[6.3 3.3 4.7 1.6]
 [5.7 3.  4.2 1.2]
 [5.  3.6 1.4 0.2]
 [6.8 2.8 4.8 1.4]
 [7.7 3.8 6.7 2.2]
 [6.3 2.8 5.1 1.5]
 [4.4 2.9 1.4 0.2]
 [5.  2.3 3.3 1. ]
 [4.8 3.  1.4 0.3]
 [5.  3.3 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [5.4 3.4 1.7 0.2]
 [5.6 3.  4.1 1.3]
 [5.4 3.9 1.3 0.4]
 [5.7 2.8 4.1 1.3]
 [6.6 3.  4.4 1.4]
 [6.1 2.9 4.7 1.4]
 [5.8 2.7 4.1 1. ]
 [6.  3.  4.8 1.8]
 [6.4 2.7 5.3 1.9]]


Exercici 5
Crea una matriu que mostri:
• La mitjana de cada característica per espècie.
• La desviació estàndard de cada característica per espècie.

In [6]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data  
target = iris.target  

species = np.unique(target)  
mean_by_species = []
std_by_species = []

for specie in species:
    data_by_specie = data[target == specie]

    mean_per_specie = np.mean(data_by_specie, axis=0)
    std_per_specie = np.std(data_by_specie, axis=0)

    mean_by_species.append(mean_per_specie)
    std_by_species.append(std_per_specie)

mean_by_species = np.array(mean_by_species)
std_by_species = np.array(std_by_species)

result_matrix = np.column_stack((mean_by_species, std_by_species))

print("Matriu que mostra la mitjana i la desviació estàndard per espècie:")
print(result_matrix)

Matriu que mostra la mitjana i la desviació estàndard per espècie:
[[5.006      3.428      1.462      0.246      0.34894699 0.37525458
  0.17191859 0.10432641]
 [5.936      2.77       4.26       1.326      0.51098337 0.31064449
  0.46518813 0.19576517]
 [6.588      2.974      5.552      2.026      0.62948868 0.31925538
  0.54634787 0.27188968]]


Exercici 6
• Calcula la quantitat de mostres per espècie.
• Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"


In [7]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data  
target = iris.target  
target_names = iris.target_names 
feature_names = iris.feature_names  

samples_per_species = {species: np.sum(target == idx) for idx, species in enumerate(target_names)}

print("Quantitat de mostres per espècie:")
for species, count in samples_per_species.items():
    print(f"{species}: {count} mostres")

sepal_length_index = feature_names.index('sepal length (cm)')
mean_sepal_length_per_species = [np.mean(data[target == idx, sepal_length_index]) for idx in range(len(target_names))]
max_mean_sepal_length_species = target_names[np.argmax(mean_sepal_length_per_species)]

print("Espècie amb la mitjana màxima de 'sepal length (cm)':")
print(max_mean_sepal_length_species)

Quantitat de mostres per espècie:
setosa: 50 mostres
versicolor: 50 mostres
virginica: 50 mostres

Espècie amb la mitjana màxima de 'sepal length (cm)':
virginica


Exercici 7
• Calcula la matriu de correlació entre les variables.
• Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho.
• Troba la mostra amb els pètals més grans.

In [4]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data  
feature_names = iris.feature_names  

correlation_matrix = np.corrcoef(data, rowvar=False)

print("Matriu de correlació entre les variables:")
print(correlation_matrix)

petal_length_index = feature_names.index('petal length (cm)')
mean_petal_length = np.mean(data[:, petal_length_index])

filtered_data = data[data[:, petal_length_index] > mean_petal_length]

print("Valors majors a la mitjana de la longitud dels pètals:")
print(filtered_data)

max_petal_length_index = np.argmax(data[:, petal_length_index])
sample_with_max_petal_length = data[max_petal_length_index]

print("Mostra amb els pètals més grans:")
print(sample_with_max_petal_length)

Matriu de correlació entre les variables:
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
Valors majors a la mitjana de la longitud dels pètals:
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.5 2.4 3.8 1.1]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 

Exercici 8
Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [7]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data  
feature_names = iris.feature_names 
target_names = iris.target_names  

sepal_length_index = feature_names.index('sepal length (cm)')
petal_length_index = feature_names.index('petal length (cm)')

mean_sepal_length_per_species = []
mean_petal_length_per_species = []

for specie in range(len(target_names)):
    data_by_specie = data[iris.target == specie]

    mean_sepal_length = np.mean(data_by_specie[:, sepal_length_index])
    mean_petal_length = np.mean(data_by_specie[:, petal_length_index])

    mean_sepal_length_per_species.append(mean_sepal_length)
    mean_petal_length_per_species.append(mean_petal_length)

max_difference_index = np.argmax(np.abs(np.array(mean_sepal_length_per_species) - np.array(mean_petal_length_per_species)))
species_with_max_difference = target_names[max_difference_index]

print("L'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals és:")
print(species_with_max_difference)

L'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals és:
setosa
